### ISSUE TITLE
亲，是否有兴趣考虑阿里闲鱼的岗位？

### ISSUE THREAD

**Issue by chengzheustc** [SmallStoneSK/Blog#16]
开发者，您好！

我是阿里闲鱼技术部的兰昊，看了您的github上的Flutter项目，与我们目前技术方向很切合，不知您是否对这边的工作机会感兴趣，希望能与您取得联系。

邮箱：chengzhe.cz@alibaba-inc.com

**Comment by SmallStoneSK** [comment]
Hi，您好
很感谢您的邀请，有点小激动~ 不过目前工作主要技术栈还是RN，Flutter是最近自己在业余时间感兴趣学习的一个点，也是才刚开始学习，应该还没达到您这边的技术要求。。

**Comment by chengzheustc** [comment]
哦这个不要紧的，这里新招进来的人之前都是没有Flutter实战开发经验的。您对技术的好奇心和热情是吸引我的地方。期望与您取得联系。
