### ISSUE TITLE
出版社编辑，希望探讨合作

### ISSUE THREAD

**Issue by zhsheditor** [SmallStoneSK/Blog#17]
您好，我是人邮IT图书策划编辑，看到您写的Flutter方面的技术文章，质量很不错，请问您是否有写书的意愿呢？我的邮箱zhangshuang@ptpress.com.cn，期待您的回复。

**Comment by SmallStoneSK** [comment]
不好意思，自认还没有这个水平，所以也没这方面过的想法。

**Comment by zhsheditor** [comment]
您好，感谢回复。是否方便加下微信或者QQ，有关您的文章，想详细交流一下。我的wx：zhsh2322，QQ：1290431392
